export const jobRoleSuggestionData = [
  { jobRole: "Software Developer" },
  { jobRole: "Web Developer" },
  { jobRole: "Mobile App Developer" },
  { jobRole: "Full Stack Developer" },
  { jobRole: "Frontend Developer" },
  { jobRole: "Backend Developer" },
  { jobRole: "DevOps Engineer" },
  { jobRole: "Data Scientist" },
  { jobRole: "Data Analyst" },
  { jobRole: "Machine Learning Engineer" },
  { jobRole: "UI/UX Designer" },
  { jobRole: "Product Manager" },
  { jobRole: "Project Manager" },
  { jobRole: "Business Analyst" },
  { jobRole: "Quality Assurance Engineer" },
  { jobRole: "Network Engineer" },
  { jobRole: "System Administrator" },
  { jobRole: "Database Administrator" },
  { jobRole: "Security Analyst" },
  { jobRole: "Sales Representative" },
  { jobRole: "Marketing Specialist" },
  { jobRole: "Customer Support Specialist" },
  { jobRole: "Human Resources Manager" },
  { jobRole: "Financial Analyst" },
  { jobRole: "Legal Counsel" },
  { jobRole: "Graphic Designer" },
  { jobRole: "Content Writer" },
  { jobRole: "Social Media Manager" },
  { jobRole: "Electrician" },
  { jobRole: "Plumber" },
  { jobRole: "Mechanical Engineer" },
  { jobRole: "Civil Engineer" },
  { jobRole: "Architect" },
  { jobRole: "Medical Doctor" },
  { jobRole: "Nurse" },
  { jobRole: "Pharmacist" },
  { jobRole: "Teacher" },
  { jobRole: "Police Officer" },
  { jobRole: "Firefighter" },
  { jobRole: "Chef" },
  { jobRole: "Waiter/Waitress" },
  { jobRole: "Accountant" },
  { jobRole: "Financial Advisor" },
  { jobRole: "Economist" },
  { jobRole: "Administrative Assistant" },
  { jobRole: "Executive Assistant" },
  { jobRole: "Operations Manager" },
  { jobRole: "Logistics Coordinator" },
  { jobRole: "Retail Sales Associate" },
  { jobRole: "Customer Service Representative" },
  { jobRole: "Event Planner" },
  { jobRole: "Photographer" },
  { jobRole: "Fitness Trainer" },
  { jobRole: "Interior Designer" },
  { jobRole: "Electrician" },
  { jobRole: "Plumber" },
  { jobRole: "Welder" },
  { jobRole: "Machinist" },
  { jobRole: "Technical Writer" },
  { jobRole: "Biomedical Engineer" },
  { jobRole: "Robotics Engineer" },
  { jobRole: "Environmental Scientist" },
  { jobRole: "Digital Marketing Specialist" },
  { jobRole: "UX Researcher" },
  { jobRole: "Financial Planner" },
  { jobRole: "Forensic Scientist" },
  { jobRole: "Dental Hygienist" },
  { jobRole: "Logistics Analyst" },
  { jobRole: "Social Worker" },
  { jobRole: "Biotechnologist" },
  { jobRole: "Radiologist" },
  { jobRole: "Geologist" },
  { jobRole: "Veterinarian" },
  { jobRole: "Phlebotomist" },
  { jobRole: "Speech Therapist" },
  { jobRole: "Librarian" },
  { jobRole: "Meteorologist" },
  { jobRole: "Dietitian" },
  { jobRole: "Fashion Designer" },
  { jobRole: "Urban Planner" },
  { jobRole: "IT Support Specialist" },
  { jobRole: "Biostatistician" },
  { jobRole: "Air Traffic Controller" },
  { jobRole: "Carpenter" },
  { jobRole: "Civil Drafter" },
  { jobRole: "Curator" },
  { jobRole: "Interpreter/Translator" },
  { jobRole: "Technical Support Engineer" },
  { jobRole: "Animator" },
  { jobRole: "Digital Artist" },
  { jobRole: "SEO Specialist" },
  { jobRole: "Cryptocurrency Analyst" },
  { jobRole: "Bioinformatician" },
  { jobRole: "Gaming Developer" },
  { jobRole: "Ethical Hacker" },
  { jobRole: "Marine Biologist" },
  { jobRole: "Astronomer" },
  { jobRole: "Speech Pathologist" },
  { jobRole: "Renewable Energy Engineer" },
  { jobRole: "Blockchain Developer" },
  { jobRole: "Virtual Reality Developer" },
  { jobRole: "Quantitative Analyst" },
  { jobRole: "Solar Panel Installer" },
  { jobRole: "Technical Illustrator" },
  { jobRole: "Wildlife Biologist" },
  { jobRole: "Legal Secretary" },
  { jobRole: "Creative Director" },
  { jobRole: "GIS Specialist" },
  { jobRole: "E-learning Developer" },
  { jobRole: "Risk Analyst" },
  { jobRole: "User Interface Artist" },
  { jobRole: "Data Engineer" },
  { jobRole: "Clinical Psychologist" },
  { jobRole: "Public Relations Specialist" },
  { jobRole: "Ethnographer" },
  { jobRole: "Nuclear Engineer" },
  { jobRole: "Food Scientist" },
  { jobRole: "Podiatrist" },
  { jobRole: "Sports Analyst" },
  { jobRole: "Quantum Physicist" },
  { jobRole: "Wind Turbine Technician" },
  { jobRole: "Cybersecurity Consultant" },
  { jobRole: "Meteorological Technician" },
  { jobRole: "Aquaculturist" },
  { jobRole: "Voice Actor" },
  { jobRole: "GIS Analyst" },
  { jobRole: "Clinical Data Manager" },
  { jobRole: "Machine Vision Engineer" },
  { jobRole: "Beekeeper" },
  { jobRole: "Biomedical Ethicist" },
  { jobRole: "Forestry Technician" },
  { jobRole: "Urban Farmer" },
  { jobRole: "Cryptocurrency Trader" },
  { jobRole: "Recycling Coordinator" },
  { jobRole: "Sustainability Consultant" },
  { jobRole: "Public Health Analyst" },
  { jobRole: "Zookeeper" },
  { jobRole: "Hydrologist" },
  { jobRole: "Documentary Filmmaker" },
  { jobRole: "Bioacoustician" },
  { jobRole: "Geographic Information Scientist" },
  { jobRole: "Cruise Ship Entertainer" },
  { jobRole: "Sports Photographer" },
  { jobRole: "Music Therapist" },
  { jobRole: "Futurist" },
  { jobRole: "Personal Shopper" },
  { jobRole: "Narrative Designer" },
  { jobRole: "Ethical Fashion Designer" },
  { jobRole: "Drone Pilot" },
  { jobRole: "Seismologist" },
  { jobRole: "Park Ranger" },
];

export const locationSuggestionData = [
  // Indian Cities
  { city: "Bangalore" },
  { city: "Mumbai" },
  { city: "Noida" },
  { city: "Nagpur" },
  { city: "Kolkata" },
  { city: "Kochi" },
  { city: "Delhi" },
  { city: "Chennai" },
  { city: "Hyderabad" },
  { city: "Pune" },
  { city: "Jaipur" },
  { city: "Ahmedabad" },
  { city: "Lucknow" },
  { city: "Surat" },
  { city: "Kanpur" },
  { city: "Patna" },
  { city: "Indore" },
  { city: "Thane" },
  { city: "Bhopal" },
  { city: "Visakhapatnam" },
  { city: "Vadodara" },
  { city: "Firozabad" },
  { city: "Ludhiana" },
  { city: "Rajkot" },
  { city: "Agra" },
  { city: "Siliguri" },
  { city: "Nashik" },
  { city: "Faridabad" },
  { city: "Meerut" },
  { city: "Rajahmundry" },
  { city: "Srinagar" },
  // Additional Indian Cities
  { city: "Kozhikode" },
  { city: "Varanasi" },
  { city: "Bhubaneswar" },
  { city: "Amritsar" },
  { city: "Dehradun" },
  { city: "Guwahati" },
  { city: "Aurangabad" },
  { city: "Mangalore" },
  { city: "Thiruvananthapuram" },
  { city: "Coimbatore" },
  { city: "Jodhpur" },
  { city: "Kollam" },
  { city: "Ghaziabad" },
  { city: "Nellore" },
  { city: "Dhanbad" },
  // Non-Indian Cities
  { city: "New York" },
  { city: "London" },
  { city: "Paris" },
  { city: "Tokyo" },
  { city: "Sydney" },
  { city: "Toronto" },
  { city: "Dubai" },
  { city: "Singapore" },
  { city: "Hong Kong" },
  { city: "Berlin" },
  { city: "Moscow" },
  { city: "Rio de Janeiro" },
  { city: "Cape Town" },
  { city: "Seoul" },
  { city: "Amsterdam" },
  { city: "Rome" },
  { city: "Stockholm" },
  { city: "Barcelona" },
  { city: "Los Angeles" },
  { city: "Vancouver" },
  // Additional Non-Indian Cities
  { city: "Beijing" },
  { city: "Shanghai" },
  { city: "Istanbul" },
  { city: "Bangkok" },
  { city: "Munich" },
  { city: "Rio de Janeiro" },
  { city: "Cape Town" },
  { city: "Seoul" },
  { city: "Amsterdam" },
  { city: "Rome" },
  { city: "Stockholm" },
  { city: "Barcelona" },
  { city: "Los Angeles" },
  { city: "Vancouver" },
  { city: "Sydney" },
  { city: "Auckland" },
  { city: "Marrakech" },
  { city: "Buenos Aires" },
  { city: "San Francisco" },
  { city: "Rio de Janeiro" },
  { city: "Cape Town" },
  { city: "Seoul" },
  { city: "Amsterdam" },
  { city: "Rome" },
  { city: "Stockholm" },
  { city: "Barcelona" },
  { city: "Los Angeles" },
  { city: "Vancouver" },
  // Add more non-Indian cities as needed
];




