export const data = {
  "status": "OK",
  "request_id": "1f279bb1-9262-4721-a8b7-1e754d457579",
  "parameters": {
    "query": "react js developer  in kolkata",
    "page": 1,
    "num_pages": 1
  },
  "data": [
    {
      "employer_name": "LTIMindtree",
      "employer_logo": "https://www.ltimindtree.com/wp-content/uploads/2022/10/LTIMindtree_Linear_2-1-LT-Blue-1-1.png",
      "employer_website": "http://www.lntinfotech.com",
      "employer_company_type": "Computer Services",
      "job_publisher": "LinkedIn",
      "job_id": "Z48iVRDICkddpkgPAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "React JS Developer",
      "job_apply_link": "https://in.linkedin.com/jobs/view/react-js-developer-at-ltimindtree-3690550352",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.5632,
      "apply_options": [
        {
          "publisher": "LinkedIn",
          "apply_link": "https://in.linkedin.com/jobs/view/react-js-developer-at-ltimindtree-3690550352",
          "is_direct": false
        },
        {
          "publisher": "Talent.com",
          "apply_link": "https://in.talent.com/view?id=33fcec329059",
          "is_direct": false
        },
        {
          "publisher": "Trabajo.org",
          "apply_link": "https://in.trabajo.org/job-1940-20230928-ea7ebcd4f02994d65321499245e2ec05",
          "is_direct": false
        },
        {
          "publisher": "Jooble",
          "apply_link": "https://in.jooble.org/jdp/-7836147986847276196/React-JS-Developer-Kolkatta",
          "is_direct": false
        },
        {
          "publisher": "Learn4Good",
          "apply_link": "https://www.learn4good.com/jobs/kolkata/india/info_technology/2631178884/e/",
          "is_direct": false
        },
        {
          "publisher": "Jobrapido.com",
          "apply_link": "https://in.jobrapido.com/jobpreview/258668762",
          "is_direct": false
        },
        {
          "publisher": "Hi.jobs-Search.org",
          "apply_link": "https://hi.jobs-search.org/technology_kolkata-c280886/react-js-developer_i1808351776",
          "is_direct": false
        },
        {
          "publisher": "WhatJobs",
          "apply_link": "https://en-in.whatjobs.com/jobs/React-JS-Developer/kolkata/26899491",
          "is_direct": false
        }
      ],
      "job_description": "We are hiring for the below skill:\n\nSkill -React JS Developer\n\nExperience - 5- 12 years\n\nLocation - Hyderabad/ Kolkata\n\nJD:\n\nWe are looking for an experienced Front-End Engineer with 8-12 years of experience in ReactJS to join our team. The ideal candidate for this role should have a passion for creating innovative, user-friendly interfaces and be able to design and develop web applications quickly and efficiently.\n\nKey Responsibilities:\n\n• Design and develop user interfaces using ReactJS\n\n• Integrate front-end applications with back-end services for data management.\n\n• Develop reusable components and libraries for future use.\n\n• Monitor and improve application performance.\n\n• Collaborate with UI/UX Designers to implement custom designs.\n\n• Develop and implement web security and data protection protocols.\n\n• Identify and troubleshoot issues with the user interface.\n\n• Stay up-to-date on the latest technologies and trends in the industry.\n\nQualifications:\n\n• 5+ years of professional experience in web application development.\n\n• Strong proficiency in ReactJS and VueJS.\n\n• Experience with HTML, CSS, and JavaScript.\n\n• Knowledge of web security, performance optimization, and debugging.\n\n• Familiarity with browser compatibility issues and solutions.\n\n• Excellent communication and problem-solving skills.\n\n• Knowledge of RESTful web services, Node.js and other web frameworks.\n\n• B.S. in Computer Science or related field.\n\nIf Interested Pease share your details on: nikita.baraskar@ltimindtree.com\n\nTotal Exp:\n\nRelv React JS:\n\nCurrent CTC:\n\nExp CTC:\n\nLoc:\n\nPref Loc\n\nNotice Period:",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1696499432,
      "job_posted_at_datetime_utc": "2023-10-05T09:50:32.000Z",
      "job_city": "Kolkata",
      "job_state": "WB",
      "job_country": "IN",
      "job_latitude": 22.572645,
      "job_longitude": 88.36389,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+js+developer++in+kolkata&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+js+developer++in+kolkata&htidocid=Z48iVRDICkddpkgPAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2024-03-11T10:04:30.000Z",
      "job_offer_expiration_timestamp": 1710151470,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 96,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": true,
        "degree_preferred": true,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3",
      "job_naics_code": "541511",
      "job_naics_name": "Custom Computer Programming Services"
    },
    {
      "employer_name": "INSPIRING-LIFE TECHNOLOGIES PRIVATE LIMITED",
      "employer_logo": null,
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "LinkedIn",
      "job_id": "FIl65QH09W57IJzDAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "React.js Developer",
      "job_apply_link": "https://in.linkedin.com/jobs/view/react-js-developer-at-inspiring-life-technologies-private-limited-3725538882",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6277,
      "apply_options": [
        {
          "publisher": "LinkedIn",
          "apply_link": "https://in.linkedin.com/jobs/view/react-js-developer-at-inspiring-life-technologies-private-limited-3725538882",
          "is_direct": false
        }
      ],
      "job_description": "Urgently required React.js Developer\n\nResponsibilities\n\nDetermine and develop user requirements for systems in production, to ensure maximum usability in the field of\n\nReactJS\n\nNodeJS\n\nElectron (Not required but good to know)\n\nTypescript AWS (AWS Amplify, Lambda,\n\nDynamoDB, S3, Cognito)\n\nGraphQL\n\nQualifications\n\nRequired. More or less the standard frameworks.\n\nwith 5+ years experience.\n\nExcellent verbal and written communication skills",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1695815864,
      "job_posted_at_datetime_utc": "2023-09-27T11:57:44.000Z",
      "job_city": null,
      "job_state": "WB",
      "job_country": "IN",
      "job_latitude": 22.659222,
      "job_longitude": 88.362785,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+js+developer++in+kolkata&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+js+developer++in+kolkata&htidocid=FIl65QH09W57IJzDAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2024-03-25T11:57:44.000Z",
      "job_offer_expiration_timestamp": 1711367864,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 60,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": [
        "React.js",
        "Node.js",
        "TypeScript",
        "AWS Lambda",
        "Amazon Web Services (AWS)",
        "Amazon Dynamodb",
        "Amazon S3",
        "Amazon Cognito",
        "GraphQL"
      ],
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "Cariva Technologies",
      "employer_logo": null,
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "Indeed",
      "job_id": "4JzScl1qfFLExdGtAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "React js Developer",
      "job_apply_link": "https://in.indeed.com/viewjob?jk=fc58ff514decd77d",
      "job_apply_is_direct": true,
      "job_apply_quality_score": 0.6313,
      "apply_options": [
        {
          "publisher": "Indeed",
          "apply_link": "https://in.indeed.com/viewjob?jk=fc58ff514decd77d",
          "is_direct": true
        },
        {
          "publisher": "Glassdoor",
          "apply_link": "https://www.glassdoor.co.in/job-listing/react-js-developer-cariva-technologies-JV_IC2901633_KO0,18_KE19,38.htm?jl=1008795317102",
          "is_direct": true
        },
        {
          "publisher": "SimplyHired",
          "apply_link": "https://www.simplyhired.co.in/job/eKjZLCFxRDkDtb_OHx_Vikkhwe2FRY4V5rwsV_EwPOtNVaamP_xO4w",
          "is_direct": false
        }
      ],
      "job_description": "• Proficient with HTML, Bootstrap and CSS.\n• - Must have worked in Agile Development along with Test-Driven Development.\n• Good understanding of CSS3,\n• HTML, JavaScript, jQuery. .\n• - Familiar with JASON and XML. .\n• Experience with React, Redux,\n\nJob Type: Full-time\n\nSalary: ₹70,000.00 - ₹120,000.00 per month\n\nBenefits:\n• Work from home\n\nSchedule:\n• Day shift\n\nSupplemental pay types:\n• Overtime pay\n\nApplication Question(s):\n• How many years of experience do you have in React ?\n\nEducation:\n• Bachelor's (Preferred)\n\nSpeak with the employer\n+91-XXXXXXXXXX",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1691060014,
      "job_posted_at_datetime_utc": "2023-08-03T10:53:34.000Z",
      "job_city": "Kolkata",
      "job_state": "WB",
      "job_country": "IN",
      "job_latitude": 22.572645,
      "job_longitude": 88.36389,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+js+developer++in+kolkata&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+js+developer++in+kolkata&htidocid=4JzScl1qfFLExdGtAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-11-15T06:35:23.000Z",
      "job_offer_expiration_timestamp": 1700030123,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": null,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": true,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": 70000,
      "job_max_salary": 120000,
      "job_salary_currency": "INR",
      "job_salary_period": "MONTH",
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "Unified Infotech",
      "employer_logo": null,
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "Indeed",
      "job_id": "Fgr0l1fkOy-6_2d2AAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "React.JS Developer",
      "job_apply_link": "https://in.indeed.com/viewjob?jk=a4c3319694d393c2",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6398,
      "apply_options": [
        {
          "publisher": "Indeed",
          "apply_link": "https://in.indeed.com/viewjob?jk=a4c3319694d393c2",
          "is_direct": false
        },
        {
          "publisher": "Glassdoor",
          "apply_link": "https://www.glassdoor.co.in/job-listing/react-js-developer-unified-infotech-JV_IC2901633_KO0,18_KE19,35.htm?jl=1008839016697",
          "is_direct": false
        },
        {
          "publisher": "SimplyHired",
          "apply_link": "https://www.simplyhired.co.in/job/GL4DAbofohFIRNL-GT73U5ref25y2SoyC2wxjIQd047KtdsBU1k5vg",
          "is_direct": false
        },
        {
          "publisher": "ITBots.in",
          "apply_link": "https://itbots.in/jobs/reactjs-developer-2023083003223664ef1164542f6",
          "is_direct": false
        }
      ],
      "job_description": "Desired Skills\n• Develop new user-facing features using React.js\n• Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model\n• Thorough understanding of React.js and its core principles\n• Experience with popular React.js workflows (such as Redux)\n• Familiarity with newer specifications of EcmaScript\n• Familiarity with RESTful APIs\n• Knowledge of modern authorization mechanisms, such as JSON Web Token\n• Familiarity with modern front-end build pipelines and tools\n• Experience with common front-end development tools such as Babel, Webpack, npm/yarn, etc.\n• Ability to understand business requirements and translate them into technical requirements\n• Familiarity with code versioning tools, such as Git, SVN.",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1693324899,
      "job_posted_at_datetime_utc": "2023-08-29T16:01:39.000Z",
      "job_city": "Kolkata",
      "job_state": "WB",
      "job_country": "IN",
      "job_latitude": 22.572645,
      "job_longitude": 88.36389,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+js+developer++in+kolkata&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+js+developer++in+kolkata&htidocid=Fgr0l1fkOy-6_2d2AAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-11-15T08:59:31.000Z",
      "job_offer_expiration_timestamp": 1700038771,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": null,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "Proficient Group",
      "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfdQhA29ZaVT7mB_HlzNlOXEhm4YRXSpMnUgsZ&s=0",
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "LinkedIn",
      "job_id": "1cCgwKCa14fWUNPMAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "React.js Developer - Javascript",
      "job_apply_link": "https://in.linkedin.com/jobs/view/react-js-developer-javascript-at-proficient-group-3719521980",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6321,
      "apply_options": [
        {
          "publisher": "LinkedIn",
          "apply_link": "https://in.linkedin.com/jobs/view/react-js-developer-javascript-at-proficient-group-3719521980",
          "is_direct": false
        }
      ],
      "job_description": "React JS - Infosys\n\nWe are looking for a great JavaScript developer who is proficient with React.js. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product is important.\n\nResponsibilities\n• Developing new user-facing features using React.js\n• Building reusable components and front-end libraries for future use\n• Translating designs and wireframes into high quality code\n• Optimizing components for maximum performance across a vast array of web-capable devices and browsers\n\nSkills\n• Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model\n• Thorough understanding of React.js and its core principles\n• Experience with popular React.js workflows (such as Flux or Redux)\n• Familiarity with newer specifications of EcmaScript\n• Experience with data structure libraries (e.g., Immutable.js)\n• Knowledge of isomorphic React is a plus\n• Familiarity with RESTful APIs\n• Knowledge of modern authorization mechanisms, such as JSON Web Token\n• Familiarity with modern front-end build pipelines and tools\n• Experience with common front-end development tools such as Babel, Webpack, NPM, etc.\n• Ability to understand business requirements and translate them into technical requirements\n• A knack for benchmarking and optimization\n• Familiarity with code versioning tools {{such as Git, SVN, and Mercurial}}\n\n(ref:hirist.com)",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1695223771,
      "job_posted_at_datetime_utc": "2023-09-20T15:29:31.000Z",
      "job_city": null,
      "job_state": "WB",
      "job_country": "IN",
      "job_latitude": 22.659222,
      "job_longitude": 88.362785,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+js+developer++in+kolkata&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+js+developer++in+kolkata&htidocid=1cCgwKCa14fWUNPMAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-10-20T15:29:34.000Z",
      "job_offer_expiration_timestamp": 1697815774,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": null,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "OpenGrowth",
      "employer_logo": null,
      "employer_website": "http://opengrowth.com",
      "employer_company_type": null,
      "job_publisher": "LinkedIn",
      "job_id": "qpCFWrhT9383PP97AAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "Interesting Job Opportunity: React.js Developer - Redux/Javascript",
      "job_apply_link": "https://in.linkedin.com/jobs/view/interesting-job-opportunity-react-js-developer-redux-javascript-at-opengrowth-3735505586",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6225,
      "apply_options": [
        {
          "publisher": "LinkedIn",
          "apply_link": "https://in.linkedin.com/jobs/view/interesting-job-opportunity-react-js-developer-redux-javascript-at-opengrowth-3735505586",
          "is_direct": false
        }
      ],
      "job_description": "About OpenGrowth\n\nOpenGrowth is a one-stop destination for people all around the world who want to develop an entrepreneurial mindset. We are dedicated to changing the world through collaboration and creativity.\n\nWe at OpenGrowth believe in nurturing the business and the entrepreneurs who will be the industry leaders of tomorrow. Everyone has the potential to become an entrepreneur if they get the environment to nurture their skills.\n\nThe company offers a thorough and strategic approach to mentoring entrepreneurs by providing holistic coaching and upskilling courses. They can learn from the diverse experience of seasoned entrepreneurs and synchronize their ideas with decisive actions.\n\nOur focus is to work with the best practices in tech and products that make people's life easier. That is why we exclusively work with entrepreneurs who are passionate about technology and are keen to build user-friendly products.\n\nWhat You'll Be Doing\n• Developing new user-facing features using React.js\n• Building reusable components and front-end libraries for future use\n• Translating designs and wireframes into high-quality code\n• Optimizing components for maximum performance across a vast array of web-capable devices and browsers\n\nWhat We Need To See\n• Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model\n• Thorough understanding of React.js and its core principles\n• Experience with popular React.js workflows (such as Flux or Redux)\n• Experience with data structure libraries (e.g., Immutable.js)\n• Knowledge of isomorphic React is a plus\n• Familiarity with RESTful APIs\n• Knowledge of modern authorization mechanisms, such as JSON Web Token\n• Familiarity with modern front-end build pipelines and tools\n• Experience with common front-end development tools such as Babel, Webpack, NPM, etc.\n• Ability to understand business requirements and translate them into technical requirements\n• A knack for benchmarking and optimization\n• Familiarity with code versioning tools {such as Git/SVN}\n• Must have at least 5 to 7 years of experience\n• Must have experience working on the applications.\n\nRemote Work - Full time\n\n(ref:hirist.com)",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1697297364,
      "job_posted_at_datetime_utc": "2023-10-14T15:29:24.000Z",
      "job_city": null,
      "job_state": "WB",
      "job_country": "IN",
      "job_latitude": 22.659222,
      "job_longitude": 88.362785,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+js+developer++in+kolkata&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+js+developer++in+kolkata&htidocid=qpCFWrhT9383PP97AAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-11-13T15:29:26.000Z",
      "job_offer_expiration_timestamp": 1699889366,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 60,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "TEKFORTUNE INC",
      "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-1EOWwXswTfNafOUGn0ohxTwRODjuuIAaaZ6s&s=0",
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "LinkedIn",
      "job_id": "UZmZdPKT1PTCmaB0AAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "Frontend Developer - React.js",
      "job_apply_link": "https://in.linkedin.com/jobs/view/frontend-developer-react-js-at-tekfortune-inc-3735504888",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6214,
      "apply_options": [
        {
          "publisher": "LinkedIn",
          "apply_link": "https://in.linkedin.com/jobs/view/frontend-developer-react-js-at-tekfortune-inc-3735504888",
          "is_direct": false
        }
      ],
      "job_description": "Role/Title : Frontend Developer (React)\n\n3 Months Contract\n\nLocation : Remote/WFH\n\nNote : Ability to work IST hours, 40 hours a week for a 3 month + contract\n\nQualifications\n\nWe are looking for talented mid level experienced Frontend Engineers to join our team on a 3 month remote contract, assignment available to start in 2-3 Description :\n• Ability to work IST hours, 40 hours a week for a 3 month contract\n• 5+ years of Frontend Engineering experience specifically with application development\n• Experience with React is required\n• Experience with SASS/ JSS TypeScript, JEST/Jasmine, PWA, Redux/Saga, GraphQL, and IndexedDB are required.\n• Experience with Webpack5, Docker Container, Kubernetes, Webpack Module Federation, Brotli, TrackJS, LernaJS are not required however preferred.\n• Strong understanding and use of REST services and JSON\n• Proven ability to write Unit & UI tests, set up dashboards and alerting, uncover and fix bugs, crashes, and other issues, in order to ensure a robust app\n• Experience working in a highly automated agile environment where changes are pushed\n\n(ref:hirist.com)",
      "job_is_remote": true,
      "job_posted_at_timestamp": 1697297379,
      "job_posted_at_datetime_utc": "2023-10-14T15:29:39.000Z",
      "job_city": null,
      "job_state": "WB",
      "job_country": "IN",
      "job_latitude": 22.659222,
      "job_longitude": 88.362785,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+js+developer++in+kolkata&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+js+developer++in+kolkata&htidocid=UZmZdPKT1PTCmaB0AAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-11-13T15:29:59.000Z",
      "job_offer_expiration_timestamp": 1699889399,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 60,
        "experience_mentioned": true,
        "experience_preferred": true
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "Tier5",
      "employer_logo": null,
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "Indeed",
      "job_id": "CL0K_KRmZMSjOkkuAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "React JS Developer",
      "job_apply_link": "https://in.indeed.com/viewjob?jk=bd4032808f08b22f",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.626,
      "apply_options": [
        {
          "publisher": "Indeed",
          "apply_link": "https://in.indeed.com/viewjob?jk=bd4032808f08b22f",
          "is_direct": false
        },
        {
          "publisher": "Glassdoor",
          "apply_link": "https://www.glassdoor.co.in/job-listing/react-js-developer-tier5-JV_IC2901633_KO0,18_KE19,24.htm?jl=1008351637953",
          "is_direct": false
        },
        {
          "publisher": "SimplyHired",
          "apply_link": "https://www.simplyhired.co.in/job/ZtzmpPkuVFGZQaTReU7LEvzi67Q1mduKO_faNjXtrQFvz7ez40Wn1w",
          "is_direct": false
        }
      ],
      "job_description": "Job Description:\n• 3+ Yrs Solid knowledge of frontend development with a minimum of 2 years of work on ReactJS\n• Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model\n• Strong & thorough understanding of React.JS and its core principles\n• Experience with popular React.JS workflows such as Redux\n• Knowledge of isomorphic React is a plus\n• Familiarity with RESTful APIs\n• Familiarity with modern front-end build pipelines and tools\n• High coding standards - understanding of test coverage best practices & test pyramid concept\n• Familiar with Continuous Delivery approach\n• Experience with Distributed and Concurrent Systems, knowing the tradeoffs between stateful/stateless and synchronous/asynchronous architectures\n• Passion about technology and its relationship with product and user experience\n• Ability to work independently - identify problems, create plans and implement solutions to them\n• Broad understanding of the concept of minimum viable product (MVP)\n• Customer is at the heart of everything you do and this empathy drives all decision you make\n• Ability to articulate complex and technical concepts to non-technical audiences\n• Knowledge/interest in payment platforms, foreign exchange & highly complex systems\n\nWhere to apply : Mail your resume to recruitment@tier5.in",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1671128558,
      "job_posted_at_datetime_utc": "2022-12-15T18:22:38.000Z",
      "job_city": "Kolkata",
      "job_state": "WB",
      "job_country": "IN",
      "job_latitude": 22.572645,
      "job_longitude": 88.36389,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+js+developer++in+kolkata&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+js+developer++in+kolkata&htidocid=CL0K_KRmZMSjOkkuAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-11-15T08:46:51.000Z",
      "job_offer_expiration_timestamp": 1700038011,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": null,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "Global Employees",
      "employer_logo": null,
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "LinkedIn",
      "job_id": "7M5oABEJ8f0ta_FaAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "Frontend Developer - React.js/Javascript",
      "job_apply_link": "https://in.linkedin.com/jobs/view/frontend-developer-react-js-javascript-at-global-employees-3733089032",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6264,
      "apply_options": [
        {
          "publisher": "LinkedIn",
          "apply_link": "https://in.linkedin.com/jobs/view/frontend-developer-react-js-javascript-at-global-employees-3733089032",
          "is_direct": false
        }
      ],
      "job_description": "Salary : Description :\n\nWe are looking for programmers with a keen eye for design for the position of front-end developer react. Front-end developers are responsible for ensuring the alignment of web design and user experience requirements, optimizing web pages for maximum efficiency, and maintaining brand consistency across all web pages, among other duties.\n\nFront-end developers are required to work in teams alongside back-end developers, graphic designers, and user experience designers to ensure all elements of web creation are consistent. This requires excellent communication and interpersonal skills.\n\nResponsibilities\n• Determining the structure and design of web pages.\n• Ensuring user experience determines design choices.\n• Developing features to enhance the user experience.\n• Striking a balance between functional and aesthetic design.\n• Ensuring web design is optimized for smartphones.\n• Building reusable code for future use.\n• Optimizing web pages for maximum speed and scalability.\n• Utilizing a variety of markup languages to write web pages.\n• Maintaining brand consistency throughout the design.\n\nQualifications :\n• Degree in computer science or related field.\n• Understanding of key design principles.\n• Proficiency in React, HTML, CSS, JavaScript, and jQuery.\n• Understanding of server-side CSS.\n• Experience with graphic design applications such as Adobe Illustrator.\n• Experience with responsive and adaptive design.\n• Understanding of SEO principles.\n• Good problem-solving skills.\n• Excellent verbal communication skills.\n• Good interpersonal skills.\n\n(ref:hirist.com)",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1697210963,
      "job_posted_at_datetime_utc": "2023-10-13T15:29:23.000Z",
      "job_city": null,
      "job_state": "WB",
      "job_country": "IN",
      "job_latitude": 22.659222,
      "job_longitude": 88.362785,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+js+developer++in+kolkata&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+js+developer++in+kolkata&htidocid=7M5oABEJ8f0ta_FaAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-11-12T15:29:24.000Z",
      "job_offer_expiration_timestamp": 1699802964,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": null,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": false,
        "degree_preferred": true,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "AVI Consulting LLP",
      "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMsiMQGmgJF7ow-BAFQunEDFrXWO1jvK4tXfQw&s=0",
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "LinkedIn",
      "job_id": "haeCFdaFOCoy8BTIAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "React JS Developer",
      "job_apply_link": "https://in.linkedin.com/jobs/view/react-js-developer-at-avi-consulting-llp-3627618016",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6353,
      "apply_options": [
        {
          "publisher": "LinkedIn",
          "apply_link": "https://in.linkedin.com/jobs/view/react-js-developer-at-avi-consulting-llp-3627618016",
          "is_direct": false
        }
      ],
      "job_description": "Job Description\n\nWe are looking for a React.js or React Native Developer to join our team.\n\nIn this role, you will be entrusted with developing JavaScript applications using React.js or React Native.\n\nApply now for the role of a React.js or React Native Developer that is opening doors for skilled, energetic developers looking for Mern Stack Developer Jobs.\n\nIf you can help us design and create multiple layers of applications while working cross-functionally across different infrastructures. You would fit perfectly if you love problem-solving, design, and creating quality offerings.\n\nResponsibilities\n• Developing existing programs by analyzing user requirements and identifying areas for modification by R&D followed by coding.\n• Develop UI in HTML, CSS, and JS and integration with the backend using REST API.\n• Translate storyboards and various use cases to create high-performing apps.\n• Write, execute, and maintain clean, reusable, and scalable code.\n• Integrate our various data storage solutions.\n• Ensure responsiveness and boost the performance of our apps.\n• Find and address the various bottlenecks and bug-fixes.\n• Work on JavaScript/Typescript using React Native/React, Redux & Node.js.\n• Help in code automation.\n\nWhat You Need To Apply (Technical Competency)\n• Previous work experience as a React.js or React Native developer for 1 year at least.\n• Professional experience in Javascript Stack / Framework.\n• Experience with Object-Oriented Programming\n• Ability to document their code.\n• Understanding accessibility and security compliance.\n• Proficient use of GIT\n• Ability to multitask and work in a fast-paced environment.\n• Self-motivated with the ability to work independently or jointly in a self-directed way.\n• Demonstrated successful development of web or mobile-based applications\n• Proven analytical and problem-solving capabilities\n• Keen attention to detail\n• Strong work ethic and desire to build industry-leading products\n• Proactive instead of reactive\n• Looking for ways to improve self and projects.\n\nInterpersonal Skills\n• Must be comfortable working in a team and independently when required.\n• Must be disciplined, proactive and self-motivated\n• Needs to have problem-solving and analytical skills\n• Good to have previous experience of direct client interaction for project briefs and updates.\n\nIf you have it all in you, we are happy to have you with us!\n\nSkills:- Javascript, Redux/Flux, Object Oriented Programming (OOPs), Git and Analytical Skills",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1686055880,
      "job_posted_at_datetime_utc": "2023-06-06T12:51:20.000Z",
      "job_city": null,
      "job_state": "WB",
      "job_country": "IN",
      "job_latitude": 22.659222,
      "job_longitude": 88.362785,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+js+developer++in+kolkata&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+js+developer++in+kolkata&htidocid=haeCFdaFOCoy8BTIAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-10-24T12:51:03.000Z",
      "job_offer_expiration_timestamp": 1698151863,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 12,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": 200000,
      "job_max_salary": 700000,
      "job_salary_currency": "INR",
      "job_salary_period": "YEAR",
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    }
  ]
}